// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAUT4hjN51X_9Mu3RuLHuPX9DVxvtLyZQ',
    appId: '1:1004947994145:web:ed2264e205914a19665560',
    messagingSenderId: '1004947994145',
    projectId: 'trilearn-ca5f3',
    authDomain: 'trilearn-ca5f3.firebaseapp.com',
    storageBucket: 'trilearn-ca5f3.firebasestorage.app',
    measurementId: 'G-5LT93V6PYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS4tmFL5fJiosfUYKwM2snMJ146tph2RM',
    appId: '1:1004947994145:android:43840b1146e2b3e4665560',
    messagingSenderId: '1004947994145',
    projectId: 'trilearn-ca5f3',
    storageBucket: 'trilearn-ca5f3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-40nMG6lQKhgo2kQqCQolOTiEd1c5qfg',
    appId: '1:1004947994145:ios:534a4cdcf16d81b9665560',
    messagingSenderId: '1004947994145',
    projectId: 'trilearn-ca5f3',
    storageBucket: 'trilearn-ca5f3.firebasestorage.app',
    androidClientId: '1004947994145-j0hr6gkohtcm1dpupjmnuqqmk6dgleii.apps.googleusercontent.com',
    iosClientId: '1004947994145-7pcenjp2fs867s0c1um72510qeu77nj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-40nMG6lQKhgo2kQqCQolOTiEd1c5qfg',
    appId: '1:1004947994145:ios:534a4cdcf16d81b9665560',
    messagingSenderId: '1004947994145',
    projectId: 'trilearn-ca5f3',
    storageBucket: 'trilearn-ca5f3.firebasestorage.app',
    androidClientId: '1004947994145-j0hr6gkohtcm1dpupjmnuqqmk6dgleii.apps.googleusercontent.com',
    iosClientId: '1004947994145-7pcenjp2fs867s0c1um72510qeu77nj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAUT4hjN51X_9Mu3RuLHuPX9DVxvtLyZQ',
    appId: '1:1004947994145:web:93a58e4a9827282d665560',
    messagingSenderId: '1004947994145',
    projectId: 'trilearn-ca5f3',
    authDomain: 'trilearn-ca5f3.firebaseapp.com',
    storageBucket: 'trilearn-ca5f3.firebasestorage.app',
    measurementId: 'G-K6BGNVV82Y',
  );
}
